[project]
name = "mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "younes285", email = "mostafa.younes2004@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dvc>=3.67.1",
    "mlflow>=3.16.0",
    "pillow>=12.3.0",
    "scikit-learn>=1.9.1",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

[project.scripts]
mlops = "mlops:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
